// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7ETY_yQtqMnh7b4xopGWi4D0Jc8-gr0',
    appId: '1:713539219957:web:218b9feacbbc4f69d230bc',
    messagingSenderId: '713539219957',
    projectId: 'conexion5b',
    authDomain: 'conexion5b.firebaseapp.com',
    storageBucket: 'conexion5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGleR_DGq_acGoGwUE5FFvizC7sxmCUG4',
    appId: '1:713539219957:android:fad5e4983f0f5e9cd230bc',
    messagingSenderId: '713539219957',
    projectId: 'conexion5b',
    storageBucket: 'conexion5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzhdqTAyr3arDNR6MfQygwkKV0SEJtgbY',
    appId: '1:713539219957:ios:569b3566ba4cdd43d230bc',
    messagingSenderId: '713539219957',
    projectId: 'conexion5b',
    storageBucket: 'conexion5b.firebasestorage.app',
    iosBundleId: 'com.example.conexionfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzhdqTAyr3arDNR6MfQygwkKV0SEJtgbY',
    appId: '1:713539219957:ios:569b3566ba4cdd43d230bc',
    messagingSenderId: '713539219957',
    projectId: 'conexion5b',
    storageBucket: 'conexion5b.firebasestorage.app',
    iosBundleId: 'com.example.conexionfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC7ETY_yQtqMnh7b4xopGWi4D0Jc8-gr0',
    appId: '1:713539219957:web:9638b5f921f5a723d230bc',
    messagingSenderId: '713539219957',
    projectId: 'conexion5b',
    authDomain: 'conexion5b.firebaseapp.com',
    storageBucket: 'conexion5b.firebasestorage.app',
  );
}
